"use client";

import Link from "next/link";
import { usePathname, useSearchParams, useRouter } from "next/navigation";
import { useChatStore } from "@/store/useChatStore";
import { useEffect, useState } from "react";
import { MoreVertical, Trash2, Edit3, Check, X, Pin, PinOff, Download } from "lucide-react";
import { Menu, MenuButton, MenuItem, MenuItems, Transition } from "@headlessui/react";
import { Fragment } from "react";
import jsPDF from "jspdf";

const RecentChats = () => {
    const searchParams = useSearchParams();
    const router = useRouter();
    const activeId = searchParams.get("id");
    const pathname = usePathname();
    const { chats, setCurrentChat, deleteChat, renameChat, togglePin } = useChatStore();
    const [editingId, setEditingId] = useState<string | null>(null);
    const [editValue, setEditValue] = useState("");

    useEffect(() => {
        if (pathname === "/chat" && activeId) {
            setCurrentChat(activeId);
        }
    }, [activeId, pathname, setCurrentChat]);

    const sortedChats = [...chats].sort((a, b) => {
        if (a.isPinned && !b.isPinned) return -1;
        if (!a.isPinned && b.isPinned) return 1;
        return b.lastUpdated - a.lastUpdated;
    });

    const handleStartEdit = (e: React.MouseEvent, id: string, title: string) => {
        e.preventDefault();
        e.stopPropagation();
        setEditingId(id);
        setEditValue(title);
    };

    const handleSaveEdit = (e: React.FormEvent | React.MouseEvent, id: string) => {
        e.preventDefault();
        e.stopPropagation();
        if (editValue.trim()) {
            renameChat(id, editValue);
        }
        setEditingId(null);
    };

    const handleCancelEdit = (e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setEditingId(null);
    };

    const handleDelete = (e: React.MouseEvent, id: string) => {
        e.preventDefault();
        e.stopPropagation();
        if (confirm("Are you sure you want to delete this chat?")) {
            deleteChat(id);
            if (activeId === id) {
                router.push("/chat");
            }
        }
    };

    const handlePin = (e: React.MouseEvent, id: string) => {
        e.preventDefault();
        e.stopPropagation();
        togglePin(id);
    };

    const handleDownloadPDF = (e: React.MouseEvent, chatId: string) => {
        e.preventDefault();
        e.stopPropagation();
        const chat = chats.find(c => c.id === chatId);
        if (!chat) return;

        const doc = new jsPDF();
        let y = 20;
        doc.setFontSize(20);
        doc.text(chat.title || "Study Session", 20, y);
        y += 15;

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated by School AI - ${new Date().toLocaleDateString()}`, 20, y);
        y += 10;

        doc.setFontSize(12);
        doc.setTextColor(0);

        chat.messages.forEach((msg) => {
            const role = msg.role === "user" ? "Student" : "Assistant";
            const lines = doc.splitTextToSize(`${role}: ${msg.content}`, 170);

            if (y + (lines.length * 7) > 280) {
                doc.addPage();
                y = 20;
            }

            doc.setFont("helvetica", "bold");
            doc.text(`${role}:`, 20, y);
            y += 7;

            doc.setFont("helvetica", "normal");
            lines.forEach((line: string) => {
                let textToPrint = line;
                if (line.startsWith(`${role}:`)) {
                    textToPrint = line.substring(role.length + 2);
                }

                if (y > 280) {
                    doc.addPage();
                    y = 20;
                }
                doc.text(textToPrint, 25, y);
                y += 6;
            });
            y += 10;
        });

        doc.save(`${chat.title || "chat"}.pdf`);
    };

    return (
        <div className="py-4 px-1">
            <div className="mb-2 px-3 text-xs font-medium text-gray-400">Recent Chats</div>
            <div className="flex flex-col">
                {sortedChats.map((item) => (
                    <div
                        key={item.id}
                        className={`group relative flex items-center rounded-xl transition-all ${pathname === "/chat" && item.id === activeId
                            ? "bg-gray-50 !text-gray-900 font-bold shadow-xs border border-gray-100/50"
                            : "text-gray-500 hover:bg-gray-25"
                            }`}
                    >
                        {editingId === item.id ? (
                            <form
                                className="flex items-center gap-1 w-full px-2 py-1.5"
                                onSubmit={(e) => handleSaveEdit(e, item.id)}
                            >
                                <input
                                    autoFocus
                                    className="flex-1 bg-white border border-primary-100 rounded px-1.5 py-0.5 text-sm outline-none text-gray-900"
                                    value={editValue}
                                    onChange={(e) => setEditValue(e.target.value)}
                                    onKeyDown={(e) => e.key === "Escape" && setEditingId(null)}
                                />
                                <button type="submit" className="text-primary-200 hover:text-primary-300">
                                    <Check className="w-4 h-4" />
                                </button>
                                <button type="button" onClick={handleCancelEdit} className="text-gray-400 hover:text-gray-600">
                                    <X className="w-4 h-4" />
                                </button>
                            </form>
                        ) : (
                            <>
                                <Link
                                    className="flex-1 truncate px-3 py-2 text-sm cursor-pointer"
                                    href={`/chat?id=${item.id}`}
                                >
                                    {item.isPinned && <Pin className="w-3 h-3 text-primary-200 shrink-0" />}
                                    <span className="truncate">{item.title}</span>
                                </Link>
                                <Menu as="div" className="relative flex mr-1">
                                    <MenuButton className="p-1 rounded hover:bg-gray-100 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <MoreVertical className="w-4 h-4 text-gray-400" />
                                    </MenuButton>
                                    <Transition
                                        as={Fragment}
                                        enter="transition ease-out duration-100"
                                        enterFrom="transform opacity-0 scale-95"
                                        enterTo="transform opacity-100 scale-100"
                                        leave="transition ease-in duration-75"
                                        leaveFrom="transform opacity-100 scale-100"
                                        leaveTo="transform opacity-0 scale-95"
                                    >
                                        <MenuItems className="absolute right-0 top-full mt-1 w-44 origin-top-right rounded-xl bg-white p-1 shadow-xl ring-1 ring-gray-900/5 focus:outline-none z-[100]">
                                            <MenuItem>
                                                {({ active }) => (
                                                    <button
                                                        onClick={(e) => handlePin(e, item.id)}
                                                        className={`${active ? "bg-gray-50 text-gray-900" : "text-gray-700"
                                                            } flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-xs font-medium`}
                                                    >
                                                        {item.isPinned ? <PinOff className="w-3.5 h-3.5 text-primary-200" /> : <Pin className="w-3.5 h-3.5" />}
                                                        {item.isPinned ? "Unpin" : "Pin"}
                                                    </button>
                                                )}
                                            </MenuItem>
                                            <MenuItem>
                                                {({ active }) => (
                                                    <button
                                                        onClick={(e) => handleDownloadPDF(e, item.id)}
                                                        className={`${active ? "bg-gray-50 text-gray-900" : "text-gray-700"
                                                            } flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-xs font-medium`}
                                                    >
                                                        <Download className="w-3.5 h-3.5" />
                                                        Export as PDF
                                                    </button>
                                                )}
                                            </MenuItem>
                                            <MenuItem>
                                                {({ active }) => (
                                                    <button
                                                        onClick={(e) => handleStartEdit(e, item.id, item.title)}
                                                        className={`${active ? "bg-gray-50 text-gray-900" : "text-gray-700"
                                                            } flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-xs font-medium`}
                                                    >
                                                        <Edit3 className="w-3.5 h-3.5" />
                                                        Rename
                                                    </button>
                                                )}
                                            </MenuItem>
                                            <div className="my-1 border-t border-gray-50" />
                                            <MenuItem>
                                                {({ active }) => (
                                                    <button
                                                        onClick={(e) => handleDelete(e, item.id)}
                                                        className={`${active ? "bg-error-0 text-error-100" : "text-error-100"
                                                            } flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-xs font-medium`}
                                                    >
                                                        <Trash2 className="w-3.5 h-3.5" />
                                                        Delete chat
                                                    </button>
                                                )}
                                            </MenuItem>
                                        </MenuItems>
                                    </Transition>
                                </Menu>
                            </>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default RecentChats;
